// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.tl.cityactivity.proto

package mtproto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// /////////////////////////////////////////////////////////////////////////////
// CityActivity <--
//   - TL_cityActivity
type CityActivity struct {
	PredicateName        string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor          TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                   int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64         `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string        `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string        `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	PhotoId              int64         `protobuf:"varint,7,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	City                 string        `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	StartTime            int64         `protobuf:"varint,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64         `protobuf:"varint,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxParticipants      int32         `protobuf:"varint,11,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	Status               int32         `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	IsGlobal             *Bool         `protobuf:"bytes,13,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"`
	ParticipantCount     int32         `protobuf:"varint,14,opt,name=participant_count,json=participantCount,proto3" json:"participant_count,omitempty"`
	IsJoined             *Bool         `protobuf:"bytes,15,opt,name=is_joined,json=isJoined,proto3" json:"is_joined,omitempty"`
	CreatorName          string        `protobuf:"bytes,16,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatedAt            int64         `protobuf:"varint,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Photos               []*Photo      `protobuf:"bytes,18,rep,name=photos,proto3" json:"photos,omitempty"`
	ChatId               int64         `protobuf:"varint,19,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CityActivity) Reset()         { *m = CityActivity{} }
func (m *CityActivity) String() string { return proto.CompactTextString(m) }
func (*CityActivity) ProtoMessage()    {}
func (*CityActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{0}
}
func (m *CityActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityActivity.Unmarshal(m, b)
}
func (m *CityActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityActivity.Marshal(b, m, deterministic)
}
func (m *CityActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityActivity.Merge(m, src)
}
func (m *CityActivity) XXX_Size() int {
	return xxx_messageInfo_CityActivity.Size(m)
}
func (m *CityActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_CityActivity.DiscardUnknown(m)
}

var xxx_messageInfo_CityActivity proto.InternalMessageInfo

func (m *CityActivity) GetPredicateName() string {
	if m != nil {
		return m.PredicateName
	}
	return ""
}

func (m *CityActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *CityActivity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CityActivity) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CityActivity) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CityActivity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CityActivity) GetPhotoId() int64 {
	if m != nil {
		return m.PhotoId
	}
	return 0
}

func (m *CityActivity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CityActivity) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CityActivity) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *CityActivity) GetMaxParticipants() int32 {
	if m != nil {
		return m.MaxParticipants
	}
	return 0
}

func (m *CityActivity) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CityActivity) GetIsGlobal() *Bool {
	if m != nil {
		return m.IsGlobal
	}
	return nil
}

func (m *CityActivity) GetParticipantCount() int32 {
	if m != nil {
		return m.ParticipantCount
	}
	return 0
}

func (m *CityActivity) GetIsJoined() *Bool {
	if m != nil {
		return m.IsJoined
	}
	return nil
}

func (m *CityActivity) GetCreatorName() string {
	if m != nil {
		return m.CreatorName
	}
	return ""
}

func (m *CityActivity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CityActivity) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

func (m *CityActivity) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

// TL_cityActivity
type TLCityActivity struct {
	Data2                *CityActivity `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivity) Reset()         { *m = TLCityActivity{} }
func (m *TLCityActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivity) ProtoMessage()    {}
func (*TLCityActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{1}
}
func (m *TLCityActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivity.Unmarshal(m, b)
}
func (m *TLCityActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivity.Merge(m, src)
}
func (m *TLCityActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivity.Size(m)
}
func (m *TLCityActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivity proto.InternalMessageInfo

func (m *TLCityActivity) GetData2() *CityActivity {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// CityActivity_Activities <--
//   - TL_cityActivity_activities
type CityActivity_Activities struct {
	PredicateName        string          `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor          TLConstructor   `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Activities           []*CityActivity `protobuf:"bytes,3,rep,name=activities,proto3" json:"activities,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CityActivity_Activities) Reset()         { *m = CityActivity_Activities{} }
func (m *CityActivity_Activities) String() string { return proto.CompactTextString(m) }
func (*CityActivity_Activities) ProtoMessage()    {}
func (*CityActivity_Activities) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{2}
}
func (m *CityActivity_Activities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityActivity_Activities.Unmarshal(m, b)
}
func (m *CityActivity_Activities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityActivity_Activities.Marshal(b, m, deterministic)
}
func (m *CityActivity_Activities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityActivity_Activities.Merge(m, src)
}
func (m *CityActivity_Activities) XXX_Size() int {
	return xxx_messageInfo_CityActivity_Activities.Size(m)
}
func (m *CityActivity_Activities) XXX_DiscardUnknown() {
	xxx_messageInfo_CityActivity_Activities.DiscardUnknown(m)
}

var xxx_messageInfo_CityActivity_Activities proto.InternalMessageInfo

func (m *CityActivity_Activities) GetPredicateName() string {
	if m != nil {
		return m.PredicateName
	}
	return ""
}

func (m *CityActivity_Activities) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *CityActivity_Activities) GetActivities() []*CityActivity {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *CityActivity_Activities) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// TL_cityActivity_activities
type TLCityActivityActivities struct {
	Data2                *CityActivity_Activities `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TLCityActivityActivities) Reset()         { *m = TLCityActivityActivities{} }
func (m *TLCityActivityActivities) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityActivities) ProtoMessage()    {}
func (*TLCityActivityActivities) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{3}
}
func (m *TLCityActivityActivities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityActivities.Unmarshal(m, b)
}
func (m *TLCityActivityActivities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityActivities.Marshal(b, m, deterministic)
}
func (m *TLCityActivityActivities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityActivities.Merge(m, src)
}
func (m *TLCityActivityActivities) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityActivities.Size(m)
}
func (m *TLCityActivityActivities) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityActivities.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityActivities proto.InternalMessageInfo

func (m *TLCityActivityActivities) GetData2() *CityActivity_Activities {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// CityActivity RPC request messages
type TLCityActivityGetActivities struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	City                 string        `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Offset               int32         `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32         `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityGetActivities) Reset()         { *m = TLCityActivityGetActivities{} }
func (m *TLCityActivityGetActivities) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityGetActivities) ProtoMessage()    {}
func (*TLCityActivityGetActivities) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{4}
}
func (m *TLCityActivityGetActivities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityGetActivities.Unmarshal(m, b)
}
func (m *TLCityActivityGetActivities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityGetActivities.Marshal(b, m, deterministic)
}
func (m *TLCityActivityGetActivities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityGetActivities.Merge(m, src)
}
func (m *TLCityActivityGetActivities) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityGetActivities.Size(m)
}
func (m *TLCityActivityGetActivities) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityGetActivities.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityGetActivities proto.InternalMessageInfo

func (m *TLCityActivityGetActivities) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityGetActivities) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *TLCityActivityGetActivities) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *TLCityActivityGetActivities) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TLCityActivityGetActivity struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                   int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityGetActivity) Reset()         { *m = TLCityActivityGetActivity{} }
func (m *TLCityActivityGetActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityGetActivity) ProtoMessage()    {}
func (*TLCityActivityGetActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{5}
}
func (m *TLCityActivityGetActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityGetActivity.Unmarshal(m, b)
}
func (m *TLCityActivityGetActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityGetActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivityGetActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityGetActivity.Merge(m, src)
}
func (m *TLCityActivityGetActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityGetActivity.Size(m)
}
func (m *TLCityActivityGetActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityGetActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityGetActivity proto.InternalMessageInfo

func (m *TLCityActivityGetActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityGetActivity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TLCityActivityCreateActivity struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Title                string        `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PhotoId              int64         `protobuf:"varint,5,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	City                 string        `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	StartTime            int64         `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64         `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MaxParticipants      int32         `protobuf:"varint,9,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	PhotoIds             []int64       `protobuf:"varint,10,rep,packed,name=photo_ids,json=photoIds,proto3" json:"photo_ids,omitempty"`
	IsGlobal             *Bool         `protobuf:"bytes,11,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityCreateActivity) Reset()         { *m = TLCityActivityCreateActivity{} }
func (m *TLCityActivityCreateActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityCreateActivity) ProtoMessage()    {}
func (*TLCityActivityCreateActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{6}
}
func (m *TLCityActivityCreateActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityCreateActivity.Unmarshal(m, b)
}
func (m *TLCityActivityCreateActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityCreateActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivityCreateActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityCreateActivity.Merge(m, src)
}
func (m *TLCityActivityCreateActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityCreateActivity.Size(m)
}
func (m *TLCityActivityCreateActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityCreateActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityCreateActivity proto.InternalMessageInfo

func (m *TLCityActivityCreateActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityCreateActivity) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TLCityActivityCreateActivity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TLCityActivityCreateActivity) GetPhotoId() int64 {
	if m != nil {
		return m.PhotoId
	}
	return 0
}

func (m *TLCityActivityCreateActivity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *TLCityActivityCreateActivity) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TLCityActivityCreateActivity) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *TLCityActivityCreateActivity) GetMaxParticipants() int32 {
	if m != nil {
		return m.MaxParticipants
	}
	return 0
}

func (m *TLCityActivityCreateActivity) GetPhotoIds() []int64 {
	if m != nil {
		return m.PhotoIds
	}
	return nil
}

func (m *TLCityActivityCreateActivity) GetIsGlobal() *Bool {
	if m != nil {
		return m.IsGlobal
	}
	return nil
}

type TLCityActivityEditActivity struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                   int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Title                string        `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description          string        `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PhotoId              int64         `protobuf:"varint,6,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	StartTime            int64         `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64         `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status               int32         `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityEditActivity) Reset()         { *m = TLCityActivityEditActivity{} }
func (m *TLCityActivityEditActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityEditActivity) ProtoMessage()    {}
func (*TLCityActivityEditActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{7}
}
func (m *TLCityActivityEditActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityEditActivity.Unmarshal(m, b)
}
func (m *TLCityActivityEditActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityEditActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivityEditActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityEditActivity.Merge(m, src)
}
func (m *TLCityActivityEditActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityEditActivity.Size(m)
}
func (m *TLCityActivityEditActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityEditActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityEditActivity proto.InternalMessageInfo

func (m *TLCityActivityEditActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityEditActivity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TLCityActivityEditActivity) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TLCityActivityEditActivity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TLCityActivityEditActivity) GetPhotoId() int64 {
	if m != nil {
		return m.PhotoId
	}
	return 0
}

func (m *TLCityActivityEditActivity) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TLCityActivityEditActivity) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *TLCityActivityEditActivity) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type TLCityActivityDeleteActivity struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                   int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityDeleteActivity) Reset()         { *m = TLCityActivityDeleteActivity{} }
func (m *TLCityActivityDeleteActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityDeleteActivity) ProtoMessage()    {}
func (*TLCityActivityDeleteActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{8}
}
func (m *TLCityActivityDeleteActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityDeleteActivity.Unmarshal(m, b)
}
func (m *TLCityActivityDeleteActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityDeleteActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivityDeleteActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityDeleteActivity.Merge(m, src)
}
func (m *TLCityActivityDeleteActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityDeleteActivity.Size(m)
}
func (m *TLCityActivityDeleteActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityDeleteActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityDeleteActivity proto.InternalMessageInfo

func (m *TLCityActivityDeleteActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityDeleteActivity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TLCityActivityJoinActivity struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                   int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	City                 string        `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityJoinActivity) Reset()         { *m = TLCityActivityJoinActivity{} }
func (m *TLCityActivityJoinActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityJoinActivity) ProtoMessage()    {}
func (*TLCityActivityJoinActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{9}
}
func (m *TLCityActivityJoinActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityJoinActivity.Unmarshal(m, b)
}
func (m *TLCityActivityJoinActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityJoinActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivityJoinActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityJoinActivity.Merge(m, src)
}
func (m *TLCityActivityJoinActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityJoinActivity.Size(m)
}
func (m *TLCityActivityJoinActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityJoinActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityJoinActivity proto.InternalMessageInfo

func (m *TLCityActivityJoinActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityJoinActivity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TLCityActivityJoinActivity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

type TLCityActivityLeaveActivity struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Id                   int64         `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLCityActivityLeaveActivity) Reset()         { *m = TLCityActivityLeaveActivity{} }
func (m *TLCityActivityLeaveActivity) String() string { return proto.CompactTextString(m) }
func (*TLCityActivityLeaveActivity) ProtoMessage()    {}
func (*TLCityActivityLeaveActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e08a1e33fdd2c33, []int{10}
}
func (m *TLCityActivityLeaveActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLCityActivityLeaveActivity.Unmarshal(m, b)
}
func (m *TLCityActivityLeaveActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLCityActivityLeaveActivity.Marshal(b, m, deterministic)
}
func (m *TLCityActivityLeaveActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLCityActivityLeaveActivity.Merge(m, src)
}
func (m *TLCityActivityLeaveActivity) XXX_Size() int {
	return xxx_messageInfo_TLCityActivityLeaveActivity.Size(m)
}
func (m *TLCityActivityLeaveActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_TLCityActivityLeaveActivity.DiscardUnknown(m)
}

var xxx_messageInfo_TLCityActivityLeaveActivity proto.InternalMessageInfo

func (m *TLCityActivityLeaveActivity) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLCityActivityLeaveActivity) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CityActivity)(nil), "mtproto.CityActivity")
	proto.RegisterType((*TLCityActivity)(nil), "mtproto.TL_cityActivity")
	proto.RegisterType((*CityActivity_Activities)(nil), "mtproto.CityActivity_Activities")
	proto.RegisterType((*TLCityActivityActivities)(nil), "mtproto.TL_cityActivity_activities")
	proto.RegisterType((*TLCityActivityGetActivities)(nil), "mtproto.TL_cityActivity_getActivities")
	proto.RegisterType((*TLCityActivityGetActivity)(nil), "mtproto.TL_cityActivity_getActivity")
	proto.RegisterType((*TLCityActivityCreateActivity)(nil), "mtproto.TL_cityActivity_createActivity")
	proto.RegisterType((*TLCityActivityEditActivity)(nil), "mtproto.TL_cityActivity_editActivity")
	proto.RegisterType((*TLCityActivityDeleteActivity)(nil), "mtproto.TL_cityActivity_deleteActivity")
	proto.RegisterType((*TLCityActivityJoinActivity)(nil), "mtproto.TL_cityActivity_joinActivity")
	proto.RegisterType((*TLCityActivityLeaveActivity)(nil), "mtproto.TL_cityActivity_leaveActivity")
}

func init() { proto.RegisterFile("schema.tl.cityactivity.proto", fileDescriptor_5e08a1e33fdd2c33) }

var fileDescriptor_5e08a1e33fdd2c33 = []byte{
	// 866 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x5e, 0xc7, 0x71, 0x7e, 0x4e, 0xf6, 0xaf, 0x03, 0xdd, 0x4e, 0xbd, 0x5d, 0xe4, 0x1a, 0x0a,
	0x81, 0x4a, 0x59, 0x29, 0x15, 0x88, 0x2b, 0xa4, 0x76, 0x2f, 0xd0, 0xa2, 0x0a, 0x55, 0x66, 0x11,
	0x02, 0x2e, 0xac, 0x59, 0x7b, 0x9a, 0x4c, 0x65, 0x7b, 0x22, 0xfb, 0xa4, 0x6a, 0x24, 0x5e, 0x81,
	0x07, 0x40, 0x3c, 0x10, 0x8f, 0xc3, 0x0d, 0x0f, 0x80, 0x3c, 0x76, 0xb2, 0x63, 0x67, 0xed, 0x56,
	0xd0, 0x5c, 0xc5, 0xe7, 0xc7, 0xe7, 0x9c, 0xf9, 0xce, 0x37, 0x9f, 0x03, 0x0f, 0xb2, 0x60, 0xce,
	0x63, 0x36, 0xc1, 0x68, 0x12, 0x08, 0x5c, 0xb1, 0x00, 0xc5, 0x6b, 0x81, 0xab, 0xc9, 0x22, 0x95,
	0x28, 0x49, 0x3f, 0x46, 0xf5, 0x60, 0xdf, 0xd5, 0xd2, 0xd2, 0xe0, 0xc9, 0xb4, 0x88, 0xdb, 0xb6,
	0xe6, 0x96, 0x29, 0xf7, 0x71, 0xb5, 0xe0, 0x59, 0x11, 0x73, 0xff, 0xe9, 0xc2, 0xfe, 0x85, 0xc0,
	0xd5, 0xd3, 0xb2, 0x24, 0x79, 0x04, 0x87, 0x8b, 0x94, 0x87, 0x22, 0x60, 0xc8, 0xfd, 0x84, 0xc5,
	0x9c, 0x1a, 0x8e, 0x31, 0x1e, 0x7a, 0x07, 0x1b, 0xef, 0xf7, 0x2c, 0xe6, 0xe4, 0x6b, 0x18, 0x05,
	0x32, 0xc9, 0x30, 0x5d, 0x06, 0x28, 0x53, 0xda, 0x71, 0x8c, 0xf1, 0xe1, 0xf4, 0x64, 0x52, 0x4e,
	0x32, 0xb9, 0x7a, 0x7e, 0x71, 0x13, 0xf5, 0xf4, 0x54, 0x72, 0x08, 0x1d, 0x11, 0x52, 0xd3, 0x31,
	0xc6, 0xa6, 0xd7, 0x11, 0x21, 0xb9, 0x07, 0xfd, 0x65, 0xc6, 0x53, 0x5f, 0x84, 0xb4, 0xab, 0x9c,
	0xbd, 0xdc, 0xbc, 0x0c, 0xc9, 0x87, 0x60, 0xa1, 0xc0, 0x88, 0x53, 0x4b, 0x0d, 0x50, 0x18, 0xc4,
	0x81, 0x51, 0xc8, 0xb3, 0x20, 0x15, 0x0b, 0x14, 0x32, 0xa1, 0x3d, 0x15, 0xd3, 0x5d, 0xe4, 0x3e,
	0x0c, 0x16, 0x73, 0x89, 0x32, 0xaf, 0xd8, 0x57, 0x15, 0xfb, 0xca, 0xbe, 0x0c, 0x09, 0x81, 0x6e,
	0x8e, 0x1f, 0x1d, 0xa8, 0xb7, 0xd4, 0x33, 0x39, 0x03, 0xc8, 0x90, 0xa5, 0xe8, 0xa3, 0x88, 0x39,
	0x1d, 0xaa, 0x17, 0x86, 0xca, 0x73, 0x25, 0x62, 0x9e, 0x57, 0xe3, 0x49, 0x58, 0x04, 0xa1, 0xa8,
	0xc6, 0x93, 0x50, 0x85, 0x3e, 0x87, 0xe3, 0x98, 0xbd, 0xf1, 0x17, 0x2c, 0x45, 0x11, 0x88, 0x05,
	0x4b, 0x30, 0xa3, 0x23, 0xc7, 0x18, 0x5b, 0xde, 0x51, 0xcc, 0xde, 0xbc, 0xd0, 0xdc, 0xe4, 0x04,
	0x7a, 0x19, 0x32, 0x5c, 0x66, 0x74, 0x5f, 0x25, 0x94, 0x16, 0xf9, 0x02, 0x86, 0x22, 0xf3, 0x67,
	0x91, 0xbc, 0x66, 0x11, 0x3d, 0x70, 0x8c, 0xf1, 0x68, 0x7a, 0xb0, 0x01, 0xf1, 0x99, 0x94, 0x91,
	0x37, 0x10, 0xd9, 0xb7, 0x2a, 0x4c, 0x1e, 0xc3, 0x1d, 0xad, 0x95, 0x1f, 0xc8, 0x65, 0x82, 0xf4,
	0x50, 0x95, 0x3b, 0xd6, 0x02, 0x17, 0xb9, 0xbf, 0x2c, 0xfc, 0x4a, 0x8a, 0x84, 0x87, 0xf4, 0xa8,
	0xa1, 0xf0, 0x77, 0x2a, 0x4c, 0x1e, 0xc2, 0x7e, 0x90, 0x72, 0x86, 0x32, 0x2d, 0x16, 0x7e, 0x5c,
	0x60, 0x5a, 0xfa, 0xd4, 0xba, 0xcf, 0x00, 0x94, 0xc9, 0x43, 0x9f, 0x21, 0xbd, 0x53, 0x80, 0x54,
	0x7a, 0x9e, 0x62, 0x7e, 0x3c, 0x05, 0x71, 0x46, 0x89, 0x63, 0x8e, 0xf7, 0xbd, 0xd2, 0xca, 0x77,
	0x1b, 0xcc, 0x19, 0xe6, 0x9b, 0xf8, 0xa0, 0xd8, 0x6d, 0x6e, 0x5e, 0x86, 0xee, 0x37, 0x70, 0x74,
	0xf5, 0xdc, 0x0f, 0x74, 0xe2, 0x3d, 0x06, 0x2b, 0x64, 0xc8, 0xa6, 0x8a, 0x6f, 0xa3, 0xe9, 0xdd,
	0xcd, 0xb4, 0x3a, 0x3d, 0xbd, 0x22, 0xc7, 0xfd, 0xcb, 0x80, 0x7b, 0xba, 0xdf, 0x2f, 0x1f, 0x04,
	0xcf, 0x76, 0xcf, 0xe0, 0x2f, 0x01, 0xd8, 0xa6, 0x1d, 0x35, 0x1d, 0xb3, 0x79, 0x5c, 0x2d, 0x31,
	0xe7, 0x73, 0xb1, 0xb3, 0xae, 0xda, 0x59, 0x61, 0xb8, 0x57, 0x60, 0xd7, 0x90, 0xf0, 0xb5, 0x77,
	0xbe, 0xaa, 0x82, 0xe2, 0xdc, 0xda, 0x45, 0x3b, 0xfc, 0x1a, 0x9f, 0x3f, 0x0d, 0x38, 0xab, 0x97,
	0x9d, 0x71, 0xd4, 0x50, 0xaa, 0x1d, 0xdf, 0x78, 0xf7, 0xe3, 0xaf, 0x2f, 0x91, 0xa9, 0x5d, 0xa2,
	0x13, 0xe8, 0xc9, 0x97, 0x2f, 0x33, 0xbe, 0x3e, 0x5c, 0x69, 0xe5, 0x67, 0x8e, 0x44, 0x2c, 0x50,
	0xdd, 0x61, 0xcb, 0x2b, 0x0c, 0x77, 0x06, 0xa7, 0xcd, 0xc3, 0xad, 0xfe, 0xc7, 0x68, 0x35, 0x6d,
	0x71, 0xff, 0xee, 0xc0, 0x47, 0xf5, 0x4e, 0x05, 0x6b, 0xdf, 0x43, 0xb3, 0x8d, 0x3e, 0x99, 0x2d,
	0xfa, 0xd4, 0x6d, 0xd7, 0x27, 0xeb, 0x76, 0x7d, 0xea, 0x35, 0xea, 0x53, 0xbf, 0x4d, 0x9f, 0x06,
	0x6f, 0xd7, 0xa7, 0xe1, 0xed, 0xfa, 0x74, 0x0a, 0xc3, 0xf5, 0x4c, 0x19, 0x05, 0xc7, 0x1c, 0x9b,
	0xde, 0xa0, 0x1c, 0xaa, 0x26, 0x52, 0xa3, 0x56, 0x91, 0x72, 0x7f, 0xef, 0xc0, 0x83, 0x3a, 0xe2,
	0x3c, 0x14, 0x3b, 0x58, 0xee, 0x0d, 0xfe, 0xdd, 0x16, 0xfc, 0xad, 0x76, 0xfc, 0x7b, 0x55, 0xfc,
	0xff, 0x3b, 0xd6, 0x37, 0x02, 0x3f, 0xd4, 0x05, 0xde, 0x7d, 0xb5, 0x4d, 0xc0, 0x90, 0x47, 0xfc,
	0xbd, 0x10, 0xb0, 0xce, 0xf6, 0xdf, 0xb6, 0xa1, 0xcf, 0x3f, 0x00, 0x3b, 0x80, 0x7e, 0xcd, 0xd3,
	0xee, 0x0d, 0x4f, 0x5d, 0xb1, 0xad, 0x38, 0x11, 0x67, 0xaf, 0x77, 0x70, 0xd0, 0xe9, 0x1f, 0x16,
	0x1c, 0x79, 0x2f, 0x2e, 0x2a, 0xff, 0x5b, 0xe6, 0x60, 0xb7, 0xa8, 0xdd, 0xa7, 0x5a, 0x9b, 0x16,
	0x55, 0xb4, 0xdf, 0x2a, 0xb0, 0xee, 0x1e, 0xf9, 0x19, 0x68, 0xa3, 0x74, 0x7d, 0xf2, 0x0e, 0x7d,
	0x56, 0xf6, 0xed, 0x1f, 0x0b, 0x77, 0x8f, 0xf8, 0x70, 0xda, 0xa6, 0x55, 0x9f, 0x35, 0x56, 0xaf,
	0x26, 0x36, 0x37, 0xf8, 0x15, 0xee, 0x37, 0x5f, 0xcd, 0x47, 0x8d, 0xe5, 0xf5, 0xb4, 0xe6, 0xe2,
	0x3f, 0xd5, 0xa6, 0xaf, 0x11, 0xbd, 0x79, 0xfa, 0x6a, 0xa2, 0x5d, 0x15, 0x17, 0x77, 0x8f, 0xfc,
	0x50, 0x9b, 0xba, 0xc2, 0xea, 0xe6, 0xa9, 0xf5, 0xb4, 0xed, 0xa2, 0x3f, 0xd6, 0x08, 0x53, 0x25,
	0x6b, 0x33, 0x61, 0x2a, 0x79, 0x5b, 0x65, 0x9f, 0x7d, 0xfc, 0xcb, 0xc3, 0x99, 0xc0, 0xf9, 0xf2,
	0x7a, 0x12, 0xc8, 0xf8, 0x1c, 0x39, 0x8b, 0x67, 0x29, 0x8b, 0xcf, 0x55, 0xce, 0x79, 0x99, 0x7b,
	0xdd, 0x53, 0x3f, 0x4f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x75, 0x52, 0xec, 0xd8, 0x0b,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCCityActivityClient is the client API for RPCCityActivity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCCityActivityClient interface {
	CityActivityGetActivities(ctx context.Context, in *TLCityActivityGetActivities, opts ...grpc.CallOption) (*CityActivity_Activities, error)
	CityActivityGetActivity(ctx context.Context, in *TLCityActivityGetActivity, opts ...grpc.CallOption) (*CityActivity, error)
	CityActivityCreateActivity(ctx context.Context, in *TLCityActivityCreateActivity, opts ...grpc.CallOption) (*CityActivity, error)
	CityActivityEditActivity(ctx context.Context, in *TLCityActivityEditActivity, opts ...grpc.CallOption) (*CityActivity, error)
	CityActivityDeleteActivity(ctx context.Context, in *TLCityActivityDeleteActivity, opts ...grpc.CallOption) (*Bool, error)
	CityActivityJoinActivity(ctx context.Context, in *TLCityActivityJoinActivity, opts ...grpc.CallOption) (*Bool, error)
	CityActivityLeaveActivity(ctx context.Context, in *TLCityActivityLeaveActivity, opts ...grpc.CallOption) (*Bool, error)
}

type rPCCityActivityClient struct {
	cc *grpc.ClientConn
}

func NewRPCCityActivityClient(cc *grpc.ClientConn) RPCCityActivityClient {
	return &rPCCityActivityClient{cc}
}

func (c *rPCCityActivityClient) CityActivityGetActivities(ctx context.Context, in *TLCityActivityGetActivities, opts ...grpc.CallOption) (*CityActivity_Activities, error) {
	out := new(CityActivity_Activities)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_getActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCityActivityClient) CityActivityGetActivity(ctx context.Context, in *TLCityActivityGetActivity, opts ...grpc.CallOption) (*CityActivity, error) {
	out := new(CityActivity)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_getActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCityActivityClient) CityActivityCreateActivity(ctx context.Context, in *TLCityActivityCreateActivity, opts ...grpc.CallOption) (*CityActivity, error) {
	out := new(CityActivity)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_createActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCityActivityClient) CityActivityEditActivity(ctx context.Context, in *TLCityActivityEditActivity, opts ...grpc.CallOption) (*CityActivity, error) {
	out := new(CityActivity)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_editActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCityActivityClient) CityActivityDeleteActivity(ctx context.Context, in *TLCityActivityDeleteActivity, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_deleteActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCityActivityClient) CityActivityJoinActivity(ctx context.Context, in *TLCityActivityJoinActivity, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_joinActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCCityActivityClient) CityActivityLeaveActivity(ctx context.Context, in *TLCityActivityLeaveActivity, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/mtproto.RPCCityActivity/cityActivity_leaveActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCCityActivityServer is the server API for RPCCityActivity service.
type RPCCityActivityServer interface {
	CityActivityGetActivities(context.Context, *TLCityActivityGetActivities) (*CityActivity_Activities, error)
	CityActivityGetActivity(context.Context, *TLCityActivityGetActivity) (*CityActivity, error)
	CityActivityCreateActivity(context.Context, *TLCityActivityCreateActivity) (*CityActivity, error)
	CityActivityEditActivity(context.Context, *TLCityActivityEditActivity) (*CityActivity, error)
	CityActivityDeleteActivity(context.Context, *TLCityActivityDeleteActivity) (*Bool, error)
	CityActivityJoinActivity(context.Context, *TLCityActivityJoinActivity) (*Bool, error)
	CityActivityLeaveActivity(context.Context, *TLCityActivityLeaveActivity) (*Bool, error)
}

// UnimplementedRPCCityActivityServer can be embedded to have forward compatible implementations.
type UnimplementedRPCCityActivityServer struct {
}

func (*UnimplementedRPCCityActivityServer) CityActivityGetActivities(ctx context.Context, req *TLCityActivityGetActivities) (*CityActivity_Activities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityGetActivities not implemented")
}
func (*UnimplementedRPCCityActivityServer) CityActivityGetActivity(ctx context.Context, req *TLCityActivityGetActivity) (*CityActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityGetActivity not implemented")
}
func (*UnimplementedRPCCityActivityServer) CityActivityCreateActivity(ctx context.Context, req *TLCityActivityCreateActivity) (*CityActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityCreateActivity not implemented")
}
func (*UnimplementedRPCCityActivityServer) CityActivityEditActivity(ctx context.Context, req *TLCityActivityEditActivity) (*CityActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityEditActivity not implemented")
}
func (*UnimplementedRPCCityActivityServer) CityActivityDeleteActivity(ctx context.Context, req *TLCityActivityDeleteActivity) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityDeleteActivity not implemented")
}
func (*UnimplementedRPCCityActivityServer) CityActivityJoinActivity(ctx context.Context, req *TLCityActivityJoinActivity) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityJoinActivity not implemented")
}
func (*UnimplementedRPCCityActivityServer) CityActivityLeaveActivity(ctx context.Context, req *TLCityActivityLeaveActivity) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityActivityLeaveActivity not implemented")
}

func RegisterRPCCityActivityServer(s *grpc.Server, srv RPCCityActivityServer) {
	s.RegisterService(&_RPCCityActivity_serviceDesc, srv)
}

func _RPCCityActivity_CityActivityGetActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityGetActivities)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityGetActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityGetActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityGetActivities(ctx, req.(*TLCityActivityGetActivities))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCityActivity_CityActivityGetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityGetActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityGetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityGetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityGetActivity(ctx, req.(*TLCityActivityGetActivity))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCityActivity_CityActivityCreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityCreateActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityCreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityCreateActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityCreateActivity(ctx, req.(*TLCityActivityCreateActivity))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCityActivity_CityActivityEditActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityEditActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityEditActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityEditActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityEditActivity(ctx, req.(*TLCityActivityEditActivity))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCityActivity_CityActivityDeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityDeleteActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityDeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityDeleteActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityDeleteActivity(ctx, req.(*TLCityActivityDeleteActivity))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCityActivity_CityActivityJoinActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityJoinActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityJoinActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityJoinActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityJoinActivity(ctx, req.(*TLCityActivityJoinActivity))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCCityActivity_CityActivityLeaveActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLCityActivityLeaveActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCCityActivityServer).CityActivityLeaveActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCCityActivity/CityActivityLeaveActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCCityActivityServer).CityActivityLeaveActivity(ctx, req.(*TLCityActivityLeaveActivity))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCCityActivity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCCityActivity",
	HandlerType: (*RPCCityActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "cityActivity_getActivities",
			Handler:    _RPCCityActivity_CityActivityGetActivities_Handler,
		},
		{
			MethodName: "cityActivity_getActivity",
			Handler:    _RPCCityActivity_CityActivityGetActivity_Handler,
		},
		{
			MethodName: "cityActivity_createActivity",
			Handler:    _RPCCityActivity_CityActivityCreateActivity_Handler,
		},
		{
			MethodName: "cityActivity_editActivity",
			Handler:    _RPCCityActivity_CityActivityEditActivity_Handler,
		},
		{
			MethodName: "cityActivity_deleteActivity",
			Handler:    _RPCCityActivity_CityActivityDeleteActivity_Handler,
		},
		{
			MethodName: "cityActivity_joinActivity",
			Handler:    _RPCCityActivity_CityActivityJoinActivity_Handler,
		},
		{
			MethodName: "cityActivity_leaveActivity",
			Handler:    _RPCCityActivity_CityActivityLeaveActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.tl.cityactivity.proto",
}
